use std::collections::BTreeMap;
use std::ffi::{OsStr, OsString};
use std::fs::{self, File, OpenOptions};
use std::io::Write;
use std::path::{Component, Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};
use clap::{CommandFactory, Parser, Subcommand};

use crate::config::validate_setup_config;

#[cfg(not(windows))]
const USER_HOME_ENVIRONMENT: &str = "HOME";
#[cfg(windows)]
const USER_HOME_ENVIRONMENT: &str = "USERPROFILE";

pub const INSTANCE_CONFIG_TEMPLATE: &str = r#"# Generated by `kintio setup` as <instance>/.env with mode 0600.
# Relative file paths resolve from that instance directory.
PORT=8888
# Fill all four WECOM values only when the WeChat KF channel is enabled.
# Leave them empty for an existing-account iLink-only deployment.
WECOM_CALLBACK_TOKEN=
WECOM_ENCODING_AES_KEY=

WECOM_CORP_ID=
WECOM_KF_SECRET=

# Codex is denied for every conversation user until IDs are explicitly allowlisted.
# Use a comma-separated list such as wm_user_a,wm_user_b.
# Wildcards are rejected; every entry must be an explicit external_userid.
WECOM_ALLOWED_USER_IDS=

# Optional self-authorization. Disabled while the trigger is empty.
# An unauthorized user must send the exact trigger as consecutive messages.
WECOM_AUTH_TRIGGER=
WECOM_AUTH_TRIGGER_COUNT=3
WECOM_AUTH_CONFIRMATION=Code accepted. You can continue the conversation.

# Optional runtime settings.
# WECOM_RECEIVE_ID defaults to WECOM_CORP_ID.
# KINTIO_DB_FILE=./data/kintio.sqlite
# Legacy TALKFERRY_DB_FILE, HARNESS_DB_FILE, and WECOM_DB_FILE aliases remain supported.
# WECOM_API_TIMEOUT_MS=10000
# WECOM_MCP_OBSERVE_MS=5000
# SHUTDOWN_TIMEOUT_MS=10000

# Enable Weixin iLink inside the combined `kintio start` runtime. Standalone
# `kintio ilink login` and `kintio ilink start` do not require this flag.
# Generate a 32-byte base64url key and keep it in the deployment secret store;
# Bot and context tokens are encrypted with it.
ILINK_ENABLED=false
# Prefer a deployment-secret value. If omitted, the service creates a private
# 0600 key file beside SQLite; never register that key with a chat Agent.
# ILINK_STORAGE_KEY=replace_with_43_character_base64url_key
# ILINK_STORAGE_KEY_FILE=./data/ilink-storage.key
# ILINK_BASE_URL=https://ilinkai.weixin.qq.com/
# ILINK_API_TIMEOUT_MS=15000
# ILINK_LONG_POLL_TIMEOUT_MS=35000
# ILINK_MAX_ACCOUNTS=20

# Codex CLI app-server uses the existing local Codex login.
CODEX_ENABLED=true
# CODEX_IMAGE_TMP_DIR=./data/codex-input
# CODEX_WORKING_DIRECTORY=./codex-workspace
"#;

pub const MANAGED_SKILL_CONTENT: &str =
    include_str!("../codex-workspace/.agents/skills/wechat-kf-reply-sop/SKILL.md");

#[derive(Debug, Parser)]
#[command(
    name = "kintio-rs",
    disable_version_flag = true,
    arg_required_else_help = true,
    about = "Native Kintio compatibility runtime"
)]
struct Cli {
    #[arg(long, global = true, value_name = "directory")]
    home: Option<OsString>,

    #[arg(long, global = true, value_name = "file")]
    config: Option<OsString>,

    #[arg(short = 'v', long, global = true)]
    version: bool,

    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Create a private instance directory and configuration.
    Setup,
}

#[derive(Clone, Debug)]
pub struct CliContext {
    cwd: PathBuf,
    environment: BTreeMap<OsString, OsString>,
    home_directory: PathBuf,
}

impl CliContext {
    pub fn system() -> Result<Self> {
        let cwd = std::env::current_dir().context("Unable to read the current directory")?;
        let environment = std::env::vars_os().collect::<BTreeMap<OsString, OsString>>();
        let home_directory = lookup_environment(&environment, USER_HOME_ENVIRONMENT)
            .map(PathBuf::from)
            .or_else(dirs::home_dir)
            .ok_or_else(|| anyhow!("Unable to find the home directory"))?;
        Ok(Self {
            cwd: absolute_path(&cwd, Path::new(".")),
            environment,
            home_directory: absolute_path(&cwd, &home_directory),
        })
    }

    #[must_use]
    pub fn new(
        cwd: PathBuf,
        home_directory: PathBuf,
        environment: BTreeMap<OsString, OsString>,
    ) -> Self {
        let cwd = absolute_path(Path::new("."), &cwd);
        Self {
            home_directory: absolute_path(&cwd, &home_directory),
            cwd,
            environment,
        }
    }

    fn environment_path(&self, name: &str) -> Option<PathBuf> {
        self.environment_value(name)
            .filter(|value| !value.is_empty())
            .map(PathBuf::from)
    }

    fn environment_value(&self, name: &str) -> Option<&OsString> {
        lookup_environment(&self.environment, name)
    }
}

fn lookup_environment<'a>(
    environment: &'a BTreeMap<OsString, OsString>,
    name: &str,
) -> Option<&'a OsString> {
    #[cfg(windows)]
    {
        environment.iter().find_map(|(key, value)| {
            key.to_string_lossy()
                .eq_ignore_ascii_case(name)
                .then_some(value)
        })
    }
    #[cfg(not(windows))]
    {
        environment.get(OsStr::new(name))
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct SetupLocation {
    pub home: PathBuf,
    pub config_file: PathBuf,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum FileState {
    Created,
    Kept,
}

impl FileState {
    const fn label(self) -> &'static str {
        match self {
            Self::Created => "created",
            Self::Kept => "kept",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum SkillState {
    Created,
    Updated,
    Current,
}

impl SkillState {
    const fn label(self) -> &'static str {
        match self {
            Self::Created => "created",
            Self::Updated => "updated",
            Self::Current => "current",
        }
    }
}

pub fn run_cli<I, T>(arguments: I, context: &CliContext, output: &mut dyn Write) -> Result<()>
where
    I: IntoIterator<Item = T>,
    T: Into<OsString> + Clone,
{
    let arguments = arguments
        .into_iter()
        .map(Into::into)
        .collect::<Vec<OsString>>();
    if arguments.len() == 1 {
        return write_help(output);
    }
    let cli = match Cli::try_parse_from(arguments) {
        Ok(cli) => cli,
        Err(error) if !error.use_stderr() => {
            write!(output, "{error}")?;
            return Ok(());
        }
        Err(error) => return Err(error.into()),
    };
    if cli.version {
        writeln!(output, "{}", env!("KINTIO_VERSION"))?;
        return Ok(());
    }
    let Some(command) = cli.command else {
        return write_help(output);
    };
    let location = resolve_location(
        cli.home.as_deref().map(Path::new),
        cli.config.as_deref().map(Path::new),
        context,
    )?;
    match command {
        Command::Setup => run_setup(&location, context, output),
    }
}

fn write_help(output: &mut dyn Write) -> Result<()> {
    let mut help = Vec::new();
    Cli::command().write_long_help(&mut help)?;
    help.push(b'\n');
    output.write_all(&help)?;
    Ok(())
}

fn resolve_location(
    explicit_home: Option<&Path>,
    explicit_config: Option<&Path>,
    context: &CliContext,
) -> Result<SetupLocation> {
    let explicit_home_value = explicit_home.filter(|value| !value.as_os_str().is_empty());
    let explicit_config_value = explicit_config.filter(|value| !value.as_os_str().is_empty());
    let configured_file = if explicit_home.is_some() && explicit_config.is_none() {
        None
    } else {
        explicit_config_value
            .map(Path::to_path_buf)
            .or_else(|| context.environment_path("KINTIO_CONFIG_FILE"))
    };
    let configured_home = if explicit_config.is_some() && explicit_home.is_none() {
        None
    } else {
        explicit_home_value
            .map(Path::to_path_buf)
            .or_else(|| context.environment_path("KINTIO_HOME"))
    };
    let config_file = configured_file
        .as_deref()
        .map(|file| absolute_path(&context.cwd, file));
    let home = if let Some(home) = configured_home {
        absolute_path(&context.cwd, &home)
    } else if let Some(file) = &config_file {
        file.parent()
            .map(Path::to_path_buf)
            .ok_or_else(|| anyhow!("Kintio config has no parent directory"))?
    } else {
        absolute_path(&context.home_directory, Path::new(".kintio"))
    };
    let config_file = config_file.unwrap_or_else(|| home.join(".env"));

    #[cfg(windows)]
    if !is_path_inside(&context.home_directory, &home)?
        || !is_path_inside(&context.home_directory, &config_file)?
    {
        bail!("Windows instances and config files must stay inside the current user profile");
    }

    Ok(SetupLocation { home, config_file })
}

fn run_setup(location: &SetupLocation, context: &CliContext, output: &mut dyn Write) -> Result<()> {
    ensure_directory(&location.home, "Kintio instance directory", false)?;
    let data_directory = location.home.join("data");
    ensure_contained_directory(&location.home, &data_directory, true)?;

    let config_inside_home = is_path_inside(&location.home, &location.config_file)?;
    let config_state = write_new_config(
        &location.config_file,
        if config_inside_home {
            Some(&location.home)
        } else {
            None
        },
    )?;
    private_regular_file(&location.config_file, "Kintio config")?.ok_or_else(|| {
        anyhow!(
            "Kintio config was not created: {}",
            location.config_file.display()
        )
    })?;

    let source = fs::read_to_string(&location.config_file).with_context(|| {
        format!(
            "Unable to read Kintio config: {}",
            location.config_file.display()
        )
    })?;
    let working_directory = validate_setup_config(&source, &context.environment, &location.home)?;
    let (skill_file, skill_state) = refresh_managed_skill(&working_directory)?;
    let default_home = context.home_directory.join(".kintio");
    let default_config = default_home.join(".env");
    let next_step = if location.home == default_home && location.config_file == default_config {
        "run \"kintio start\"."
    } else {
        "run \"kintio start\" with the same --home and --config options."
    };

    write!(
        output,
        "Kintio setup complete.\nHome: {}\nConfig: {} ({})\nAgent skill: {} ({})\nEdit the config, run \"codex login status\", then {}\n",
        location.home.display(),
        location.config_file.display(),
        config_state.label(),
        skill_file.display(),
        skill_state.label(),
        next_step,
    )
    .context("Unable to write setup output")?;
    Ok(())
}

fn write_new_config(file: &Path, containment_root: Option<&Path>) -> Result<FileState> {
    let parent = file
        .parent()
        .ok_or_else(|| anyhow!("Kintio config has no parent directory: {}", file.display()))?;
    if let Some(root) = containment_root {
        ensure_contained_directory(root, parent, false)?;
    } else {
        ensure_directory(parent, "Target directory", false)?;
    }
    if private_regular_file(file, "Kintio config")?.is_some() {
        return Ok(FileState::Kept);
    }

    let (temporary, mut output) = create_temporary(parent, file.file_name().unwrap_or_default())?;
    let guard = TemporaryFile::new(temporary.clone());
    output
        .write_all(INSTANCE_CONFIG_TEMPLATE.as_bytes())
        .with_context(|| format!("Unable to write temporary config: {}", temporary.display()))?;
    output
        .sync_all()
        .with_context(|| format!("Unable to sync temporary config: {}", temporary.display()))?;
    drop(output);

    match fs::hard_link(&temporary, file) {
        Ok(()) => {
            sync_directory(parent)?;
            drop(guard);
            Ok(FileState::Created)
        }
        Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {
            private_regular_file(file, "Kintio config")?.ok_or_else(|| {
                anyhow!(
                    "Target file appeared with an invalid type: {}",
                    file.display()
                )
            })?;
            Ok(FileState::Kept)
        }
        Err(error) => Err(error)
            .with_context(|| format!("Unable to install Kintio config: {}", file.display())),
    }
}

fn refresh_managed_skill(working_directory: &Path) -> Result<(PathBuf, SkillState)> {
    ensure_directory(working_directory, "Agent working directory", false)?;
    let skill_file = working_directory
        .join(".agents")
        .join("skills")
        .join("wechat-kf-reply-sop")
        .join("SKILL.md");
    let skill_directory = skill_file
        .parent()
        .ok_or_else(|| anyhow!("Managed Skill has no parent directory"))?;
    ensure_contained_directory(working_directory, skill_directory, true)?;

    let existing = regular_file(&skill_file, "Managed Skill")?;
    if existing.is_some()
        && fs::read_to_string(&skill_file)
            .with_context(|| format!("Unable to read managed Skill: {}", skill_file.display()))?
            == MANAGED_SKILL_CONTENT
    {
        return Ok((skill_file, SkillState::Current));
    }

    let (temporary, mut output) =
        create_temporary(skill_directory, skill_file.file_name().unwrap_or_default())?;
    let guard = TemporaryFile::new(temporary.clone());
    output
        .write_all(MANAGED_SKILL_CONTENT.as_bytes())
        .with_context(|| format!("Unable to write managed Skill: {}", temporary.display()))?;
    output
        .sync_all()
        .with_context(|| format!("Unable to sync managed Skill: {}", temporary.display()))?;
    drop(output);
    fs::rename(&temporary, &skill_file)
        .with_context(|| format!("Unable to install managed Skill: {}", skill_file.display()))?;
    sync_directory(skill_directory)?;
    drop(guard);
    regular_file(&skill_file, "Managed Skill")?
        .ok_or_else(|| anyhow!("Managed Skill was not created: {}", skill_file.display()))?;
    Ok((
        skill_file,
        if existing.is_some() {
            SkillState::Updated
        } else {
            SkillState::Created
        },
    ))
}

fn create_temporary(directory: &Path, target_name: &OsStr) -> Result<(PathBuf, File)> {
    for _ in 0..128 {
        let mut random = [0_u8; 12];
        getrandom::fill(&mut random).context("Unable to obtain temporary-file randomness")?;
        let suffix = random
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        let name = format!(
            ".{}.{}.{}.tmp",
            target_name.to_string_lossy(),
            std::process::id(),
            suffix,
        );
        let file_path = directory.join(name);
        let mut options = OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }
        match options.open(&file_path) {
            Ok(file) => return Ok((file_path, file)),
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {}
            Err(error) => {
                return Err(error).with_context(|| {
                    format!("Unable to create temporary file in {}", directory.display())
                });
            }
        }
    }
    bail!(
        "Unable to allocate a unique temporary file in {}",
        directory.display()
    )
}

struct TemporaryFile {
    path: PathBuf,
}

impl TemporaryFile {
    fn new(path: PathBuf) -> Self {
        Self { path }
    }
}

impl Drop for TemporaryFile {
    fn drop(&mut self) {
        let _ = fs::remove_file(&self.path);
    }
}

fn ensure_contained_directory(root: &Path, directory: &Path, private_contents: bool) -> Result<()> {
    let existing_ancestor = nearest_existing_ancestor(directory)?;
    if !is_path_inside(root, &existing_ancestor)? {
        bail!(
            "Instance path escapes through a symbolic link: {}",
            existing_ancestor.display()
        );
    }
    let relative = contained_relative_path(root, directory)?;
    let mut current = root.to_path_buf();
    let mut components = relative.components().peekable();
    while let Some(component) = components.next() {
        current.push(component.as_os_str());
        let is_leaf = components.peek().is_none();
        ensure_directory(
            &current,
            "Private directory path",
            private_contents && is_leaf,
        )?;
    }
    if relative.as_os_str().is_empty() {
        assert_trusted_directory(root, "Private directory path", private_contents)?;
    }
    if !is_path_inside(root, directory)? {
        bail!(
            "Instance path escapes through a symbolic link: {}",
            directory.display()
        );
    }
    Ok(())
}

fn contained_relative_path(root: &Path, directory: &Path) -> Result<PathBuf> {
    #[cfg(windows)]
    let (root, directory) = (canonical_path(root)?, canonical_path(directory)?);
    #[cfg(not(windows))]
    let (root, directory) = (root.to_path_buf(), directory.to_path_buf());

    directory
        .strip_prefix(&root)
        .map(Path::to_path_buf)
        .map_err(|_| {
            anyhow!(
                "Instance path is not lexically inside its root: {}",
                directory.display()
            )
        })
}

fn ensure_directory(path: &Path, label: &str, private_contents: bool) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() || !metadata.is_dir() {
                bail!("{label} is not a regular directory: {}", path.display());
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            let mut builder = fs::DirBuilder::new();
            builder.recursive(true);
            #[cfg(unix)]
            {
                use std::os::unix::fs::DirBuilderExt;
                builder.mode(0o700);
            }
            builder.create(path).with_context(|| {
                format!("Unable to create private directory: {}", path.display())
            })?;
        }
        Err(error) => {
            return Err(error)
                .with_context(|| format!("Unable to inspect directory: {}", path.display()));
        }
    }
    assert_trusted_directory(path, label, private_contents)
}

fn assert_trusted_directory(path: &Path, label: &str, private_contents: bool) -> Result<()> {
    let metadata = fs::symlink_metadata(path)
        .with_context(|| format!("Unable to inspect {label}: {}", path.display()))?;
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        bail!("{label} is not a regular directory: {}", path.display());
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::{MetadataExt, PermissionsExt};
        if metadata.uid() != rustix::process::getuid().as_raw() {
            bail!(
                "{label} is not owned by the current user: {}",
                path.display()
            );
        }
        let forbidden = if private_contents { 0o077 } else { 0o022 };
        if metadata.permissions().mode() & forbidden != 0 {
            bail!("{label} has unsafe permissions: {}", path.display());
        }
    }
    #[cfg(not(unix))]
    let _ = private_contents;
    Ok(())
}

fn private_regular_file(path: &Path, label: &str) -> Result<Option<fs::Metadata>> {
    let metadata = regular_file(path, label)?;
    let Some(metadata) = metadata else {
        return Ok(None);
    };
    #[cfg(unix)]
    {
        use std::os::unix::fs::{MetadataExt, PermissionsExt};
        if metadata.uid() != rustix::process::getuid().as_raw() {
            bail!(
                "{label} is not owned by the current user: {}",
                path.display()
            );
        }
        if metadata.permissions().mode() & 0o077 != 0 {
            bail!(
                "{label} must not be accessible by group or other users: {}",
                path.display()
            );
        }
    }
    Ok(Some(metadata))
}

fn regular_file(path: &Path, label: &str) -> Result<Option<fs::Metadata>> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => {
            return Err(error)
                .with_context(|| format!("Unable to inspect {label}: {}", path.display()));
        }
    };
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        bail!("{label} is not a regular file: {}", path.display());
    }
    Ok(Some(metadata))
}

fn nearest_existing_ancestor(path: &Path) -> Result<PathBuf> {
    let mut ancestor = path.to_path_buf();
    loop {
        match fs::symlink_metadata(&ancestor) {
            Ok(_) => return Ok(ancestor),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                if !ancestor.pop() {
                    return Ok(path.to_path_buf());
                }
            }
            Err(error) => {
                return Err(error).with_context(|| {
                    format!("Unable to inspect path ancestor: {}", ancestor.display())
                });
            }
        }
    }
}

pub(crate) fn is_path_inside(root: &Path, candidate: &Path) -> Result<bool> {
    let root = canonical_path(root)?;
    let candidate = canonical_path(candidate)?;
    #[cfg(windows)]
    {
        let root = root.to_string_lossy().to_lowercase();
        let candidate = candidate.to_string_lossy().to_lowercase();
        Ok(candidate == root
            || candidate
                .strip_prefix(&root)
                .is_some_and(|suffix| suffix.starts_with(['\\', '/'])))
    }
    #[cfg(not(windows))]
    {
        Ok(candidate.starts_with(root))
    }
}

fn canonical_path(path: &Path) -> Result<PathBuf> {
    let mut ancestor = path.to_path_buf();
    let mut suffix = Vec::<OsString>::new();
    loop {
        match fs::canonicalize(&ancestor) {
            Ok(mut canonical) => {
                for component in suffix.iter().rev() {
                    canonical.push(component);
                }
                return Ok(canonical);
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                let name = ancestor.file_name().map(OsStr::to_os_string);
                if !ancestor.pop() {
                    return Ok(path.to_path_buf());
                }
                if let Some(name) = name {
                    suffix.push(name);
                }
            }
            Err(error) => {
                return Err(error)
                    .with_context(|| format!("Unable to resolve path: {}", ancestor.display()));
            }
        }
    }
}

pub(crate) fn absolute_path(base: &Path, value: &Path) -> PathBuf {
    let source = if value.is_absolute() {
        value.to_path_buf()
    } else {
        base.join(value)
    };
    let mut normalized = PathBuf::new();
    for component in source.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                if !normalized.pop() {
                    normalized.push(component.as_os_str());
                }
            }
            Component::Prefix(_) | Component::RootDir | Component::Normal(_) => {
                normalized.push(component.as_os_str());
            }
        }
    }
    normalized
}

#[cfg(unix)]
fn sync_directory(path: &Path) -> Result<()> {
    File::open(path)
        .and_then(|directory| directory.sync_all())
        .with_context(|| format!("Unable to sync directory: {}", path.display()))
}

#[cfg(not(unix))]
fn sync_directory(_path: &Path) -> Result<()> {
    Ok(())
}
