-- Frozen, sanitized SQLite schema and facts generated by Kintio master@9a0c775.
-- This is an immutable migration contract. Do not regenerate it from a newer schema.
PRAGMA foreign_keys = OFF;
BEGIN IMMEDIATE;
CREATE TABLE agent_artifacts (
          token_hash TEXT NOT NULL,
          ref TEXT NOT NULL,
          bytes BLOB NOT NULL,
          filename TEXT NOT NULL,
          content_type TEXT NOT NULL,
          metadata_json TEXT CHECK (metadata_json IS NULL OR json_valid(metadata_json)),
          created_at INTEGER NOT NULL,
          PRIMARY KEY (token_hash, ref),
          FOREIGN KEY (token_hash) REFERENCES agent_sessions(token_hash)
            ON DELETE CASCADE
        ) STRICT, WITHOUT ROWID;
CREATE TABLE agent_sessions (
          token_hash TEXT PRIMARY KEY,
          source_message_key TEXT NOT NULL,
          open_kfid TEXT NOT NULL,
          external_userid TEXT NOT NULL,
          channel TEXT NOT NULL DEFAULT 'wechat_kf'
            CHECK (channel IN ('wechat_kf', 'weixin_ilink')),
          reply_window_id INTEGER,
          boundary_inbox_seq INTEGER NOT NULL CHECK (boundary_inbox_seq >= 0),
          memory_thread_id TEXT NOT NULL DEFAULT '',
          media_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(media_json)),
          expires_at INTEGER NOT NULL,
          closed_at INTEGER NOT NULL DEFAULT 0,
          created_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL,
          FOREIGN KEY (source_message_key, open_kfid, external_userid)
            REFERENCES inbound_messages(
              message_key, open_kfid, external_userid
            ) ON DELETE CASCADE
        ) STRICT;
CREATE TABLE authorizations (
          external_userid TEXT PRIMARY KEY,
          authorized INTEGER NOT NULL DEFAULT 0 CHECK (authorized IN (0, 1)),
          consecutive_matches INTEGER NOT NULL DEFAULT 0
            CHECK (consecutive_matches >= 0),
          last_open_kfid TEXT NOT NULL DEFAULT '',
          last_message_key TEXT NOT NULL DEFAULT '',
          authorized_at INTEGER NOT NULL DEFAULT 0,
          updated_at INTEGER NOT NULL
        ) STRICT;
CREATE TABLE conversations (
          open_kfid TEXT NOT NULL,
          external_userid TEXT NOT NULL,
          thread_id TEXT NOT NULL DEFAULT '',
          memory_thread_id TEXT NOT NULL DEFAULT '',
          updated_at INTEGER NOT NULL,
          PRIMARY KEY (open_kfid, external_userid)
        ) STRICT, WITHOUT ROWID;
CREATE TABLE delivery_failures (
          wecom_msgid TEXT PRIMARY KEY,
          fail_type INTEGER NOT NULL,
          observed_at INTEGER NOT NULL,
          matched_attempt_key TEXT NOT NULL DEFAULT '',
          matched_at INTEGER NOT NULL DEFAULT 0
        ) STRICT;
CREATE TABLE ilink_account_secrets (
          account_key TEXT PRIMARY KEY,
          account_generation INTEGER NOT NULL CHECK (account_generation > 0),
          nonce TEXT NOT NULL,
          ciphertext TEXT NOT NULL,
          auth_tag TEXT NOT NULL,
          updated_at INTEGER NOT NULL,
          FOREIGN KEY (account_key) REFERENCES ilink_accounts(account_key)
            ON DELETE CASCADE
        ) STRICT, WITHOUT ROWID;
CREATE TABLE ilink_accounts (
          account_key TEXT PRIMARY KEY,
          provider_account_id TEXT NOT NULL UNIQUE,
          owner_peer_id TEXT NOT NULL,
          base_url TEXT NOT NULL,
          generation INTEGER NOT NULL DEFAULT 1 CHECK (generation > 0),
          status TEXT NOT NULL DEFAULT 'active'
            CHECK (status IN ('active', 'paused', 'disabled', 'revoked')),
          pause_until INTEGER NOT NULL DEFAULT 0,
          cursor TEXT NOT NULL DEFAULT '',
          cursor_updated_at INTEGER NOT NULL DEFAULT 0,
          created_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL
        ) STRICT, WITHOUT ROWID;
CREATE TABLE ilink_enrollment_audit (
          offer_id TEXT PRIMARY KEY,
          source_message_key TEXT NOT NULL,
          source_open_kfid TEXT NOT NULL,
          source_external_userid TEXT NOT NULL,
          account_key TEXT NOT NULL DEFAULT '',
          result TEXT NOT NULL
            CHECK (result IN ('confirmed', 'expired', 'failed', 'cancelled')),
          offered_at INTEGER NOT NULL,
          completed_at INTEGER NOT NULL
        ) STRICT, WITHOUT ROWID;
CREATE TABLE ilink_inbound_images (
          message_key TEXT NOT NULL,
          position INTEGER NOT NULL CHECK (position >= 0),
          account_key TEXT NOT NULL,
          peer_id TEXT NOT NULL,
          secret_generation INTEGER NOT NULL CHECK (secret_generation >= 0),
          nonce TEXT NOT NULL,
          ciphertext TEXT NOT NULL,
          auth_tag TEXT NOT NULL,
          created_at INTEGER NOT NULL,
          PRIMARY KEY (message_key, position),
          FOREIGN KEY (message_key, account_key, peer_id)
            REFERENCES inbound_messages(message_key, open_kfid, external_userid)
            ON DELETE CASCADE
        ) STRICT, WITHOUT ROWID;
CREATE TABLE ilink_login_offers (
          offer_id TEXT PRIMARY KEY,
          source_message_key TEXT NOT NULL,
          source_open_kfid TEXT NOT NULL,
          source_external_userid TEXT NOT NULL,
          secret_generation INTEGER NOT NULL CHECK (secret_generation >= 0),
          nonce TEXT NOT NULL,
          ciphertext TEXT NOT NULL,
          auth_tag TEXT NOT NULL,
          api_base_url TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'waiting'
            CHECK (status IN (
              'waiting', 'scanned', 'confirmed', 'expired', 'failed', 'cancelled'
            )),
          expires_at INTEGER NOT NULL,
          last_polled_at INTEGER NOT NULL DEFAULT 0,
          error_code TEXT NOT NULL DEFAULT '',
          created_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL
        ) STRICT, WITHOUT ROWID;
CREATE TABLE ilink_reply_window_secrets (
          reply_window_id INTEGER PRIMARY KEY,
          nonce TEXT NOT NULL,
          ciphertext TEXT NOT NULL,
          auth_tag TEXT NOT NULL,
          updated_at INTEGER NOT NULL,
          FOREIGN KEY (reply_window_id)
            REFERENCES ilink_reply_windows(reply_window_id) ON DELETE CASCADE
        ) STRICT, WITHOUT ROWID;
CREATE TABLE ilink_reply_windows (
          reply_window_id INTEGER PRIMARY KEY AUTOINCREMENT,
          account_key TEXT NOT NULL,
          peer_id TEXT NOT NULL,
          account_generation INTEGER NOT NULL CHECK (account_generation > 0),
          source_message_key TEXT NOT NULL UNIQUE,
          source_inbox_seq INTEGER NOT NULL CHECK (source_inbox_seq > 0),
          provider_seq INTEGER,
          issued_at INTEGER NOT NULL,
          expires_at INTEGER NOT NULL CHECK (expires_at > issued_at),
          max_sends INTEGER NOT NULL DEFAULT 10 CHECK (max_sends BETWEEN 1 AND 10),
          next_send_index INTEGER NOT NULL DEFAULT 0 CHECK (next_send_index >= 0),
          reserved_send_count INTEGER NOT NULL DEFAULT 0
            CHECK (reserved_send_count >= 0),
          transmitted_send_count INTEGER NOT NULL DEFAULT 0
            CHECK (transmitted_send_count >= 0),
          state TEXT NOT NULL DEFAULT 'open'
            CHECK (state IN ('open', 'superseded', 'closed', 'cancelled')),
          secret_generation INTEGER NOT NULL CHECK (secret_generation >= 0),
          created_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL,
          FOREIGN KEY (account_key) REFERENCES ilink_accounts(account_key),
          FOREIGN KEY (source_message_key) REFERENCES inbound_messages(message_key),
          CHECK (reserved_send_count + transmitted_send_count <= max_sends)
        ) STRICT;
CREATE TABLE inbound_media (
          media_seq INTEGER PRIMARY KEY AUTOINCREMENT,
          message_key TEXT NOT NULL,
          open_kfid TEXT NOT NULL,
          external_userid TEXT NOT NULL,
          position INTEGER NOT NULL CHECK (position >= 0),
          kind TEXT NOT NULL,
          media_id TEXT NOT NULL,
          filename TEXT NOT NULL DEFAULT '',
          sent_at INTEGER NOT NULL DEFAULT 0,
          remembered_at INTEGER NOT NULL,
          UNIQUE (message_key, position),
          FOREIGN KEY (message_key, open_kfid, external_userid)
            REFERENCES inbound_messages(
              message_key, open_kfid, external_userid
            ) ON DELETE CASCADE
        ) STRICT;
CREATE TABLE inbound_messages (
          inbox_seq INTEGER PRIMARY KEY AUTOINCREMENT,
          message_key TEXT NOT NULL UNIQUE,
          open_kfid TEXT NOT NULL,
          msgid TEXT NOT NULL,
          external_userid TEXT NOT NULL DEFAULT '',
          channel TEXT NOT NULL DEFAULT 'wechat_kf'
            CHECK (channel IN ('wechat_kf', 'weixin_ilink')),
          origin TEXT NOT NULL,
          msg_type TEXT NOT NULL,
          sent_at INTEGER NOT NULL DEFAULT 0,
          status TEXT NOT NULL CHECK (status IN ('received','processing','preparing','ready','completed','steering','steered','absorbed','failed','ignored','suppressed')),
          deferred INTEGER NOT NULL DEFAULT 0 CHECK (deferred IN (0, 1)),
          primary_message_key TEXT,
          payload_json TEXT CHECK (payload_json IS NULL OR json_valid(payload_json)),
          codex_turn_id TEXT NOT NULL DEFAULT '',
          client_input_id TEXT NOT NULL DEFAULT '',
          steering_boundary INTEGER NOT NULL DEFAULT 0,
          error_message TEXT NOT NULL DEFAULT '',
          created_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL,
          UNIQUE (open_kfid, msgid),
          UNIQUE (message_key, open_kfid, external_userid),
          FOREIGN KEY (primary_message_key)
            REFERENCES inbound_messages(message_key)
        ) STRICT;
CREATE TABLE send_attempts (
          attempt_key TEXT PRIMARY KEY,
          source_message_key TEXT NOT NULL,
          open_kfid TEXT NOT NULL,
          external_userid TEXT NOT NULL,
          channel TEXT NOT NULL DEFAULT 'wechat_kf'
            CHECK (channel IN ('wechat_kf', 'weixin_ilink')),
          reply_window_id INTEGER,
          send_index INTEGER NOT NULL CHECK (send_index >= 0 AND send_index < 1000),
          source TEXT NOT NULL,
          sent_type TEXT NOT NULL,
          payload_json TEXT CHECK (payload_json IS NULL OR json_valid(payload_json)),
          metadata_json TEXT CHECK (metadata_json IS NULL OR json_valid(metadata_json)),
          fingerprint TEXT NOT NULL,
          client_message_id TEXT NOT NULL UNIQUE,
          status TEXT NOT NULL CHECK (status IN ('pending','sending','accepted','failed','uncertain')),
          wecom_msgid TEXT NOT NULL DEFAULT '',
          error_code TEXT NOT NULL DEFAULT '',
          error_message TEXT NOT NULL DEFAULT '',
          fail_type INTEGER NOT NULL DEFAULT 0,
          created_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL,
          UNIQUE (source_message_key, send_index),
          FOREIGN KEY (source_message_key, open_kfid, external_userid)
            REFERENCES inbound_messages(
              message_key, open_kfid, external_userid
            ),
          FOREIGN KEY (reply_window_id)
            REFERENCES ilink_reply_windows(reply_window_id)
        ) STRICT;
CREATE TABLE sync_cursors (
          open_kfid TEXT PRIMARY KEY,
          cursor TEXT NOT NULL,
          updated_at INTEGER NOT NULL
        ) STRICT;
INSERT INTO "agent_sessions" ("token_hash", "source_message_key", "open_kfid", "external_userid", "channel", "reply_window_id", "boundary_inbox_seq", "memory_thread_id", "media_json", "expires_at", "closed_at", "created_at", "updated_at") VALUES ('dc2e657568bff71a60c03fa7f68996768a41895d2bbd04bc1d5a6a9153a9e205', 'legacy-wechat-message-key', 'ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'shared-peer', 'wechat_kf', NULL, 1, '01900000-0000-7000-8000-00000000aa02', '[{"ref":"media:0","messageKey":"legacy-wechat-message-key","openKfId":"ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","externalUserId":"shared-peer","kind":"image","mediaId":"wechat-media","filename":"wechat.png","sentAt":100,"rememberedAt":110}]', 4102444800000, 0, 120, 120);
INSERT INTO "authorizations" ("external_userid", "authorized", "consecutive_matches", "last_open_kfid", "last_message_key", "authorized_at", "updated_at") VALUES ('shared-peer', 1, 3, 'ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'legacy-wechat-message-key', 80, 80);
INSERT INTO "conversations" ("open_kfid", "external_userid", "thread_id", "memory_thread_id", "updated_at") VALUES ('ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'shared-peer', '01900000-0000-7000-8000-00000000aa01', '01900000-0000-7000-8000-00000000aa02', 250);
INSERT INTO "ilink_account_secrets" ("account_key", "account_generation", "nonce", "ciphertext", "auth_tag", "updated_at") VALUES ('ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 1, 'AAAAAAAAAAAAAAAA', 'AQ', 'AAAAAAAAAAAAAAAAAAAAAA', 220);
INSERT INTO "ilink_accounts" ("account_key", "provider_account_id", "owner_peer_id", "base_url", "generation", "status", "pause_until", "cursor", "cursor_updated_at", "created_at", "updated_at") VALUES ('ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'fixture-bot@im.bot', 'shared-peer', 'https://fixture.invalid', 1, 'active', 0, 'legacy-ilink-cursor', 220, 50, 220);
INSERT INTO "ilink_inbound_images" ("message_key", "position", "account_key", "peer_id", "secret_generation", "nonce", "ciphertext", "auth_tag", "created_at") VALUES ('legacy-ilink-message-key', 0, 'ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'shared-peer', 7, 'AAAAAAAAAAAAAAAA', 'Ag', 'AAAAAAAAAAAAAAAAAAAAAA', 210);
INSERT INTO "ilink_reply_window_secrets" ("reply_window_id", "nonce", "ciphertext", "auth_tag", "updated_at") VALUES (7, 'AAAAAAAAAAAAAAAA', 'Aw', 'AAAAAAAAAAAAAAAAAAAAAA', 230);
INSERT INTO "ilink_reply_windows" ("reply_window_id", "account_key", "peer_id", "account_generation", "source_message_key", "source_inbox_seq", "provider_seq", "issued_at", "expires_at", "max_sends", "next_send_index", "reserved_send_count", "transmitted_send_count", "state", "secret_generation", "created_at", "updated_at") VALUES (7, 'ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'shared-peer', 1, 'legacy-ilink-message-key', 2, 2, 200, 86400200, 10, 1, 0, 1, 'open', 7, 200, 230);
INSERT INTO "inbound_media" ("media_seq", "message_key", "open_kfid", "external_userid", "position", "kind", "media_id", "filename", "sent_at", "remembered_at") VALUES (1, 'legacy-wechat-message-key', 'ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'shared-peer', 0, 'image', 'wechat-media', 'wechat.png', 100, 110);
INSERT INTO "inbound_media" ("media_seq", "message_key", "open_kfid", "external_userid", "position", "kind", "media_id", "filename", "sent_at", "remembered_at") VALUES (2, 'legacy-ilink-message-key', 'ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'shared-peer', 0, 'image', 'ilink-media', 'ilink.png', 200, 210);
INSERT INTO "inbound_messages" ("inbox_seq", "message_key", "open_kfid", "msgid", "external_userid", "channel", "origin", "msg_type", "sent_at", "status", "deferred", "primary_message_key", "payload_json", "codex_turn_id", "client_input_id", "steering_boundary", "error_message", "created_at", "updated_at") VALUES (1, 'legacy-wechat-message-key', 'ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'wechat-provider-message', 'shared-peer', 'wechat_kf', 'customer', 'text', 100, 'processing', 0, NULL, '{"id":"wechat-provider-message","messageKey":"legacy-wechat-message-key","origin":"customer","type":"text","rawType":"text","sentAt":100,"sync":{"cursor":"legacy-cursor","index":0},"conversation":{"channel":"wechat_kf","accountKey":"ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","peerId":"shared-peer"},"text":"legacy WeChat","summary":"legacy WeChat","attributes":{},"attachments":[{"kind":"image","mediaId":"wechat-media","filename":"wechat.png"}]}', 'legacy-turn-wechat', 'legacy-client-wechat', 0, '', 100, 100);
INSERT INTO "inbound_messages" ("inbox_seq", "message_key", "open_kfid", "msgid", "external_userid", "channel", "origin", "msg_type", "sent_at", "status", "deferred", "primary_message_key", "payload_json", "codex_turn_id", "client_input_id", "steering_boundary", "error_message", "created_at", "updated_at") VALUES (2, 'legacy-ilink-message-key', 'ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'ilink-provider-message', 'shared-peer', 'weixin_ilink', 'customer', 'text', 200, 'steering', 0, 'legacy-wechat-message-key', '{"id":"ilink-provider-message","messageKey":"legacy-ilink-message-key","origin":"customer","type":"text","rawType":"text","sentAt":200,"sync":{"cursor":"legacy-cursor","index":1},"conversation":{"channel":"weixin_ilink","accountKey":"ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","peerId":"shared-peer"},"text":"legacy iLink","summary":"legacy iLink","attributes":{"provider":"weixin_ilink","providerSeq":2},"attachments":[{"kind":"image","mediaId":"ilink:0","filename":"ilink.png","status":"unresolved"}]}', 'legacy-turn-ilink', 'legacy-client-ilink', 7, '', 200, 200);
INSERT INTO "send_attempts" ("attempt_key", "source_message_key", "open_kfid", "external_userid", "channel", "reply_window_id", "send_index", "source", "sent_type", "payload_json", "metadata_json", "fingerprint", "client_message_id", "status", "wecom_msgid", "error_code", "error_message", "fail_type", "created_at", "updated_at") VALUES ('legacy-ilink-attempt', 'legacy-ilink-message-key', 'ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'shared-peer', 'weixin_ilink', 7, 0, 'mcp_tool', 'text', '{"content":"legacy reply"}', '{"direction":2}', 'legacy-fingerprint', 'legacy-client-message', 'accepted', 'legacy-provider-send', '', '', 0, 220, 230);
INSERT INTO "sync_cursors" ("open_kfid", "cursor", "updated_at") VALUES ('ia_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'legacy-wechat-cursor', 90);
CREATE INDEX agent_session_source_idx
          ON agent_sessions(source_message_key, closed_at, expires_at);
CREATE UNIQUE INDEX conversation_thread_idx
          ON conversations(thread_id) WHERE thread_id <> '';
CREATE UNIQUE INDEX ilink_active_owner_idx
          ON ilink_accounts(owner_peer_id)
          WHERE status IN ('active', 'paused');
CREATE INDEX ilink_inbound_images_created_idx
          ON ilink_inbound_images(created_at);
CREATE UNIQUE INDEX ilink_one_open_window_idx
          ON ilink_reply_windows(account_key, peer_id) WHERE state = 'open';
CREATE UNIQUE INDEX ilink_one_pending_offer_idx
          ON ilink_login_offers(source_open_kfid, source_external_userid)
          WHERE status IN ('waiting', 'scanned');
CREATE INDEX ilink_reply_windows_expiry_idx
          ON ilink_reply_windows(expires_at, state);
CREATE INDEX ilink_reply_windows_updated_idx
          ON ilink_reply_windows(updated_at, state);
CREATE INDEX inbound_deferred_idx
          ON inbound_messages(deferred, status, inbox_seq);
CREATE INDEX inbound_pending_idx
          ON inbound_messages(status, open_kfid, external_userid, inbox_seq);
CREATE INDEX inbound_primary_idx
          ON inbound_messages(primary_message_key, inbox_seq);
CREATE INDEX media_conversation_idx
          ON inbound_media(open_kfid, external_userid, remembered_at DESC);
CREATE INDEX send_conversation_idx
          ON send_attempts(open_kfid, external_userid, updated_at DESC);
CREATE INDEX send_status_idx
          ON send_attempts(channel, status, created_at, send_index);
CREATE UNIQUE INDEX send_wecom_msgid_idx
          ON send_attempts(wecom_msgid) WHERE wecom_msgid <> '';
CREATE TRIGGER ilink_attempt_window_insert_guard
        BEFORE INSERT ON send_attempts WHEN (
          (NEW.channel = 'wechat_kf' AND NEW.reply_window_id IS NOT NULL) OR
          (NEW.channel = 'weixin_ilink' AND (NEW.reply_window_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM ilink_reply_windows AS window
            WHERE window.reply_window_id = NEW.reply_window_id
              AND window.account_key = NEW.open_kfid
              AND window.peer_id = NEW.external_userid
          )))
        ) BEGIN SELECT RAISE(ABORT, 'send attempt channel/window mismatch'); END;
CREATE TRIGGER ilink_attempt_window_update_guard
        BEFORE UPDATE OF channel, reply_window_id, open_kfid,
          external_userid ON send_attempts WHEN (
          (NEW.channel = 'wechat_kf' AND NEW.reply_window_id IS NOT NULL) OR
          (NEW.channel = 'weixin_ilink' AND (NEW.reply_window_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM ilink_reply_windows AS window
            WHERE window.reply_window_id = NEW.reply_window_id
              AND window.account_key = NEW.open_kfid
              AND window.peer_id = NEW.external_userid
          )))
        ) BEGIN SELECT RAISE(ABORT, 'send attempt channel/window mismatch'); END;
CREATE TRIGGER ilink_session_window_insert_guard
        BEFORE INSERT ON agent_sessions WHEN (
          (NEW.channel = 'wechat_kf' AND NEW.reply_window_id IS NOT NULL) OR
          (NEW.channel = 'weixin_ilink' AND (NEW.reply_window_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM ilink_reply_windows AS window
            WHERE window.reply_window_id = NEW.reply_window_id
              AND window.account_key = NEW.open_kfid
              AND window.peer_id = NEW.external_userid
              AND window.source_inbox_seq = NEW.boundary_inbox_seq
              AND window.state = 'open'
          )))
        ) BEGIN SELECT RAISE(ABORT, 'agent session channel/window mismatch'); END;
CREATE TRIGGER ilink_session_window_update_guard
        BEFORE UPDATE OF channel, reply_window_id, open_kfid,
          external_userid, boundary_inbox_seq ON agent_sessions WHEN (
          (NEW.channel = 'wechat_kf' AND NEW.reply_window_id IS NOT NULL) OR
          (NEW.channel = 'weixin_ilink' AND (NEW.reply_window_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM ilink_reply_windows AS window
            WHERE window.reply_window_id = NEW.reply_window_id
              AND window.account_key = NEW.open_kfid
              AND window.peer_id = NEW.external_userid
              AND window.source_inbox_seq = NEW.boundary_inbox_seq
              AND window.state = 'open'
          )))
        ) BEGIN SELECT RAISE(ABORT, 'agent session channel/window mismatch'); END;
CREATE TRIGGER ilink_window_delete_guard
        BEFORE DELETE ON ilink_reply_windows WHEN EXISTS (
          SELECT 1 FROM agent_sessions WHERE reply_window_id = OLD.reply_window_id
        ) BEGIN SELECT RAISE(ABORT, 'reply window still has agent sessions'); END;
CREATE TRIGGER ilink_window_source_insert_guard
        BEFORE INSERT ON ilink_reply_windows WHEN NOT EXISTS (
          SELECT 1 FROM inbound_messages AS inbound
          WHERE inbound.message_key = NEW.source_message_key
            AND inbound.open_kfid = NEW.account_key
            AND inbound.external_userid = NEW.peer_id
            AND inbound.channel = 'weixin_ilink'
        ) BEGIN SELECT RAISE(ABORT, 'reply window source mismatch'); END;
CREATE TRIGGER ilink_window_source_update_guard
        BEFORE UPDATE OF source_message_key, account_key, peer_id
          ON ilink_reply_windows WHEN NOT EXISTS (
          SELECT 1 FROM inbound_messages AS inbound
          WHERE inbound.message_key = NEW.source_message_key
            AND inbound.open_kfid = NEW.account_key
            AND inbound.external_userid = NEW.peer_id
            AND inbound.channel = 'weixin_ilink'
        ) BEGIN SELECT RAISE(ABORT, 'reply window source mismatch'); END;
PRAGMA user_version = 21;
COMMIT;
PRAGMA foreign_keys = ON;


